//Generated By build.js Tue Mar 19 2019 14:48:56 GMT+0800 (中国标准时间)
const color = require("./src/random/color.js");
const date = require("./src/random/date.js");
const email = require("./src/random/email.js");
const image = require("./src/random/image.js");
const ip = require("./src/random/ip.js");
const name = require("./src/random/name.js");
const number = require("./src/random/number.js");
const phoneNumber = require("./src/random/phoneNumber.js");
const region = require("./src/random/region.js");
const text = require("./src/random/text.js");
const url = require("./src/random/url.js");

module.exports.default = module.exports = {
	color,
	date,
	email,
	image,
	ip,
	name,
	number,
	phoneNumber,
	region,
	text,
	url
}